export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const FETCH_MENU = 'FETCH_MENU';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';
export const FAILED_SIGN_IN = 'FAILED_SIGN_IN';

export const REQUEST_FETCH_POSTS = 'REQUEST_FETCH_POSTS';
export const SUCCESS_FETCH_POSTS = 'SUCCESS_FETCH_POSTS';
export const FAILED_FETCH_POSTS = 'FAILED_FETCH_POSTS';
